### ISSUE TITLE
Syntax highlight and user story detection issue

### ISSUE THREAD

**Issue by scorchio** [bawigga/nvalt-prime#11]
Hi Brian --

I've found something is a bit off: for me, syntax highlight seems to be broken (no highlight even when I'm trying to use the same code as in the README) and the user story detection is broken as well. I've checked the inspector and I see two errors:

- `ReferenceError: Can't find variable: GTD_NOTES` (app.js:11948)
- `Failed to load resource: The requested URL was not found on this server.` (file:///Users/<my username>/Library/Application%20Support/nvALT/dist/jquery.min.map)

I will check this and let you know if I find something.

Kind regards,
Zoltán

**Comment by scorchio** [comment]
This is the first time I've seen this load resource issue, as I don't usually work on jQuery. The following StackOverflow Q&A made me realize that the jquery.min.map 404 might be irrelevant to the issue: http://stackoverflow.com/questions/18365315/jquerys-jquery-1-10-2-min-map-is-triggering-a-404-not-found

**Comment by scorchio** [comment]
If I run `hljs.initHighlighting();` from the console after the page is loaded, everything seems to work fine.

**Comment by bawigga** [comment]
@scorchio weird, I'll take a look!

**Comment by bawigga** [comment]
This has been fixed. There was a JS error that was preventing the function your pointed out from being run. `git pull` latest and you should be good to go.
