### ISSUE TITLE
Underscore is Undefined

### ISSUE THREAD

**Issue by ryanfitzer** [bawigga/nvalt-prime#17]
Checkboxes weren't rendering. Console error shows:

```
[Error] ReferenceError: Can't find variable: _
	global code (app.js, line 46)
```

No 404 on loading any dependencies, but I don't see Underscore (or Lodash) declared anywhere.

**Comment by bawigga** [comment]
Sorry about that! Can you please pull latest? Needed to rebuild `dist/app.js` which should now have all those dependencies.
