### ISSUE TITLE
Checkbox doesn't work.

### ISSUE THREAD

**Issue by umeyuki** [bawigga/nvalt-prime#19]
In my case only checkbox doesn't work.

![nvaltprime-checkbox](https://cloud.githubusercontent.com/assets/738594/6890558/8d1524de-d6e8-11e4-8a33-8ef8fb97f48e.gif)

My environments:
- OS X 10.9.5 Mavericks
- mvALT Version 2.2b (111)

The markdown of that document
---
~~~ 
[fa-github]

    Class SomeClass
        def someMethod
        end
    end

[ ]  - checkbox  
[x] - checked  
[]   - check @done
~~~

**Comment by umeyuki** [comment]
The markdown of document is here.
---
[fa-github]

    Class SomeClass
        def someMethod
        end
    end

[ ]  - checkbox  
[x] - checked  
[]   - check @done

**Comment by umeyuki** [comment]
I'm sorry. I will comment on gitter.

**Comment by bawigga** [comment]
Let's keep this issue tracked here on github. 

Can you see if there are any JS errors in your console? Open nvALT, open the preview for that document, right click anywhere in the preview and click Inspect Element. You should get a safari like debugging window. At the top you should see a red warning icon, click that and you should see a console with javascript errors. Paste anything you find here.

**Comment by umeyuki** [comment]
This is result.
![nvalt-prime-js-error](https://cloud.githubusercontent.com/assets/738594/6910566/d2c3d4f6-d78f-11e4-9d18-c48c5f100522.jpg)

"ReferenceError: Can't find variable: _  app.js 46"

**Comment by bawigga** [comment]
I recently changed the template.html file to use `dist/app.js`. A recent merge didn't update that file which caused the issue you were seeing. 

```bash
cd ~/Library/Application\ Support/nvALT/
git pull origin master
```

This should be fixed with the latest commit!
