### ISSUE TITLE
There is no application set to open the URL about:blank

### ISSUE THREAD

**Issue by andyinabox** [bawigga/nvalt-prime#23]
![screenshot 2017-02-01 08 41 03](https://cloud.githubusercontent.com/assets/151084/22509058/78830150-e85a-11e6-9f03-05abb95638fd.png)

I'm getting the above message when I attempt to reload the preview window after installing nvalt-prime. Any ideas?

**Comment by andyinabox** [comment]
Actually, this seems unrelated to nvalt-prime. I reverted back to the default nvalt settings & I'm still getting the error.

**Comment by bwiggs** [comment]
@andyinabox Hopefully this error sorted itself out for you.

Been a while since I've worked on this project or used NVAlt. Google Keep/Quiver is now my current goto for notes.
