### ISSUE TITLE
GFM fenced code black language syntax identifiers not parsed

### ISSUE THREAD

**Issue by acusti** [bawigga/nvalt-prime#3]
The language syntax identifiers in a fenced code block, like “```js”, are not parsed out and applied as a class to the code block, as they should be for highlight.js to do its magic.

**Comment by bawigga** [comment]
Hi @acusti , sorry for not responding to this. I had no idea people were even using this and must have missed the github notifications. I'm thrilled to have PRs!

Let's split issues into their own tickets so we can track them all separately.
